version: "3"
services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: XperienceDb
      MYSQL_ROOT_HOST: "%"

  api:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      PORT: 8080
      DB_USERNAME: "root"
      DB_PASSWORD: "password"
      DB_NAME: "XperienceDb"
      DB_HOST: mysql
